version: "3"

services:
  web:
    container_name: "pav_web"
    build:
      context: .
      args:
        - APP_DEBUG=$APP_DEBUG
    ports:
      - "10080:80"
    volumes:
      - .:/var/www/
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/php/7.2/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - ./.docker/php/7.2/php.ini:/usr/local/etc/php/conf.d/my-app.ini
    links:
    - db
    - redis
    - mailcatcher

  mailcatcher:
    image: yappabe/mailcatcher
    container_name: "pav_mailcatcher"
    ports:
      - 10025:1025
      - 10088:1080
  db:
    image: mysql:5.7.12
    container_name: "pav_mysql"
    ports:
      - "10326:3306"
    volumes:
      - ./.docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./.docker/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./.db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=pav
  redis:
    image: redis
    container_name: "pav_redis"
    ports:
      - "10379:6379"
volumes:
  redis-data:
    driver: local
